// ... existing code ...
-      - name: Install Crawl4AI
-        run: pip install -U crawl4ai
-
-      - name: Run crawler
-        run: python generate_context.py
+      - name: Install Crawl4AI + Playwright
+        run: |
+          pip install -U "crawl4ai==0.6.3" playwright
+          python -m playwright install --with-deps chromium
+
+      - name: Run crawler
+        run: python generate_context.py
// ... existing code ...
